services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_contactus_widget
    ports:
      - "8087:80"
      - "8448:443"
    volumes:
      - ./docker/nginx_vite/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx_vite/ssl:/etc/nginx/ssl:ro
      - ./www:/usr/share/nginx/html:ro
    restart: unless-stopped
